# Generated by Django 5.2.6 on 2025-09-11 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('career_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('domain', models.CharField(max_length=100)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('education_path', models.TextField(blank=True)),
                ('expected_salary', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('text', 'Text'), ('likert', 'Likert')], default='mcq', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.JSONField(blank=True, null=True)),
                ('weightage', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('graduate', 'Graduate'), ('professional', 'Professional'), ('admin', 'Admin')], default='student', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(default='open', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('media_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('transcript', models.TextField(blank=True)),
                ('rating_avg', models.FloatField(default=0.0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('file_url', models.URLField(blank=True)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('story_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rname', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=100)),
                ('story_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/')),
                ('image_url', models.URLField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stories', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_stories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('education_level', models.CharField(blank=True, max_length=200)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.career')),
            ],
            options={
                'unique_together': {('user', 'career')},
            },
        ),
    ]
