# Generated by Django 5.2.6 on 2025-09-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='career',
            name='demand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='career',
            name='experience',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='career',
            name='growth',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='career',
            name='salary_range',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
