# Generated by Django 5.2.6 on 2025-09-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_career_company_career_demand_career_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimedia',
            old_name='description',
            new_name='transcript',
        ),
        migrations.AddField(
            model_name='multimedia',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='type',
            field=models.CharField(choices=[('Video', 'Video'), ('Podcast', 'Podcast'), ('Explainer', 'Explainer')], default='Video', max_length=20),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='multimedia/'),
        ),
    ]
