# Generated by Django 5.2.6 on 2025-09-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_description_multimedia_transcript_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='views_count',
            new_name='download_count',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='tag',
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resource',
            name='target_audience',
            field=models.CharField(choices=[('Student', 'Student'), ('Graduate', 'Graduate'), ('Professional', 'Professional'), ('All', 'All')], default='All', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('PDF', 'PDF Document'), ('Checklist', 'Checklist'), ('Infographic', 'Infographic')], default='PDF', max_length=100),
        ),
    ]
