# Generated by Django 5.2.6 on 2025-09-13 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_views_count_resource_download_count_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='multimedia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.multimedia'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.resource'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.career'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'career', 'resource', 'multimedia')},
        ),
    ]
